### PR TITLE
wip spinner candidate

### PR DESCRIPTION
**Pull request by Dhq**

### CODE REVIEW

**Review by victoriatomzik — APPROVED** [review]

**Comment by LifeofMichal** [comment]
Are the Travis failures because of the storyshots?

**Comment by victoriatomzik** [comment]
> Are the Travis failures because of the storyshots?

Seems so

**Review by victoriatomzik — COMMENTED** [review]
@Dhq Should we do something about it?

**Review by victoriatomzik — CHANGES_REQUESTED** [review]
-

**Review by nn-davsko — APPROVED** [review]
Looks good, what's wip about it, design decision? :)

**Comment by Dhq** [comment]
Sorry that this has been lingering for so long. I haven't heard of any decisions to act on this WIP so I'll close it for now.. :)

**Pull request closed without merging**
